# Generated by Django 4.2.16 on 2024-11-17 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('name_source', models.CharField(max_length=20, null=True)),
                ('date_message', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cat', models.CharField(choices=[('FIN', 'Finance'), ('WRD', 'Worlds'), ('СIT', 'City'), ('ANM', 'Animals'), ('TCH', 'Technology'), ('PRG', 'Programming')], default='FIN', max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='LineNews.news')),
            ],
        ),
    ]
